---
title: "Install_BMS_Guide"
author: "Malini"
date: "May 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\newpage


# Load packages/project
```{r load_packages, warning=FALSE, message=FALSE, echo=FALSE}

# install the packages
install.packages('ProjectTemplate')
install.packages('tidyverse')
install.packages('broom')
install.packages('rpart')
install.packages('ROCR')
install.packages('partykit')
install.packages('modelr')
install.packages('randomForest')
install.packages('devtools')
install.packages('roxygen2')
install.packages('caret')
install.packages('e1071')
install.packages('reshape')
install.packages('packrat')
# load the packages
library('ProjectTemplate')
library(tidyverse)
library(broom)
library(rpart)
library(ROCR)
library(partykit)
library(modelr)
library(randomForest)
library(devtools)
library(roxygen2)
library(caret)
library(packrat)
```

# Setting up project BMS_DevOps
```{BMS_DEVOPS, warning=FALSE, message=FALSE, echo=FALSE}

create.project("BMS_DEVOPS")

```

# Copying the data 
```{Copy Data, warning=FALSE, message=FALSE, echo=FALSE}

# Copy from github link to "data" folder under the project BMS_DEVOPS
# https://github.com/MaliniChatterjee/csx415_project/tree/master/Bank_Marketing/data
# Also ensure the directory structure has docs,graphs,reports folders.
```
# Set working directory
```{setwd, warning=FALSE, message=FALSE, echo=FALSE}

#setwd("PATH_TO_BMS_DEVOPS_DIRECTORY")
#Sample Windows path 
setwd("C:\\Users\\chatt\\OneDrive\\Documents\\Bank_Marketing")
library('ProjectTemplate')
load.project()
```
# Using Packrat Unbundle
```{unbundle, warning=FALSE, message=FALSE, echo=FALSE}

#copy the packrat bundle from github <URL>
#Sample Windows path where to copy 
setwd("C:\\Users\\chatt\\OneDrive\\Documents\\Bank_Marketing")
library('packrat')
packrat::unbundle()
# this would copy the bms2 package which we need to deploy and execute
```

# Alternate option copy the package from github
```{package_creation, warning=FALSE, message=FALSE, echo=FALSE}

#copy the package contents from github <URL>
#Sample Windows path where to copy 
setwd("C:\\Users\\chatt\\OneDrive\\Documents\\Bank_Marketing")
library('devtools')
create("bms2")
# this would create the bms2 packages folder under working directory.
# It should have the R folder and Description/Namespace/Rproj created.
# Copy the contents of the package from github 
# https://github.com/MaliniChatterjee/csx415_project/tree/master/Bank_Marketing/bms2
# Need to install this new package now
# setwd("C:\\Users\\chatt\\OneDrive\\Documents\\Bank_Marketing\\bms2")
# document()
# setwd(..)
# install(bms2)
```

# Executing the code
```{run, warning=FALSE, message=FALSE, echo=FALSE}
#set the working directory
#ensure the folder bms2 in copied under this working directory you set
setwd("C:\\Users\\chatt\\OneDrive\\Documents\\Bank_Marketing")
library(devtools)
install(bms2)
bms2::Master(#pass the working directory as input parameter#)
```

# Validating results
```{validate, warning=FALSE, message=FALSE, echo=FALSE}
# Ensure the model Rds created in "data" folder
# Ensure all exploratory data analysis plots, Decision Tree, ROC plot are in "graphs" folder
# Ensure the AUC, CUT_OFF, Accuracy, Kappa populated as results on console
# Ensure the sample test data gives row id 14 as Y (probability .782) and rest N. The telemarketer should call this customer for the new product subscription.
```

